ARG ELK_VERSION

# https://github.com/elastic/kibana-docker
FROM docker.arvancloud.ir/kibana:${ELK_VERSION}
ARG ELK_VERSION

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>